#!/usr/local/bin/perl

use strict;
use warnings;
use English;
use Benchmark;
use File::Path;
use File::Basename;
use File::Copy;

print <<WARNING;

My job is to run STD_syntax_highlight over all the tests in t/spec.
And since STD.pm is slow at the moment, this is going to take 
too much time.

You have been warned ;-)
You can press CTRL-C when you feel bored.

WARNING

my $dir_to_test = shift @ARGV || '../../t/spec/';
my $fail = 0;
my $success = 0;
my @files = sort `find $dir_to_test -name '*.t'`;
chomp(@files);
$OUTPUT_AUTOFLUSH = 1;

my $total = 0+@files;
print "Going to run $total tests... Maybe watch a movie meanwhile?\n";

my $HILITE = "STD_syntax_highlight";
my $start_time = new Benchmark;
my @failed;
for my $file (@files) {
    my $html_file = $file;
    $html_file =~ s/\.t$/.html/;
    $html_file =~ s/^\.\.\/\.\.\/t\/spec/html/;
    my ($html_filename,$html_path,$html_suffix) = fileparse($html_file);
    mkpath $html_path;
   
    #run the process and time it
    print "\n$file" . "\n    -> $html_file\n";
    my $t0 = new Benchmark;
    system "./$HILITE --clean-html $file >$html_file";
    print "It took " . 
        timestr(timediff(new Benchmark,$t0),"noc") . "\n";

    if ($CHILD_ERROR) {
        push(@failed,$file);
        $fail++;
        # catch those pesky CTRL-Cs
        if($CHILD_ERROR &= 127) {
            print "CTRL-C detected... bye bye\n";
            last;
        }
    } else {
	    $success++;
	    print "ok\n";
    }
}

printf "\nPassed $success/$total, %6.2f%%\n", $success/$total * 100;
print "It took " .
    timestr(timediff(new Benchmark,$start_time),"noc") . "\n";

if (@failed) {
    print "Failed tests:\n";
    for my $file (@failed) {
    	print "$file\n";
    }
}

print "\nCopying javascript and css files to html directory..\n";
copy("$HILITE.js","html/$HILITE.js") or die "Could not copy: $OS_ERROR\n";
copy("$HILITE.css", "html/$HILITE.css") or die "Could not copy: $OS_ERROR\n";
print "\nThe output is now in the html directory. Thanks for your time ;-)\n";

