#!/usr/local/bin/perl

use STD;
use utf8;

use Actions;

my $failures = 0;

@ARGV = 'CORE.setting' unless @ARGV;

for my $file (@ARGV) {
    warn $file,"\n" if @ARGV > 1;
    my $setting = "CORE";
    $setting = "NULL" if $file eq 'CORE.setting';
    my $r;
    eval {
        $r = STD->parsefile($file, setting => $setting, actions => 'Actions')->{'_ast'};
    };
    if ($@) {
	warn $@;
	$failures++;
    }
}
my ($time, $vsz) = split(' ', `ps -o "time= vsz=" $$`);
$time =~ s/^00://;
$vsz =~ s/\d\d\d$/m/;
if ($failures) {
    if ($vsz) {
	warn "std FAILED $time $vsz @ARGV\n";
    }
    else {
	warn "std FAILED @ARGV\n";
    }
    exit $failures;
}
elsif ($vsz) {
    warn "ok $time $vsz @ARGV\n";
}
else {
    warn "ok @ARGV\n";
}

