#!/usr/local/bin/perl

use STD;
use DumpMatch;
use utf8;
use YAML::XS;
use Encode;
use strict;
use warnings;
use Getopt::Long;
my $nocolor = 0;
my $horizontal = 0;
my $yaml = 0;
my $mark_arrays;
GetOptions("nocolor"=>\$nocolor,"horizontal"=>\$horizontal,"yaml"=>\$yaml,"mark-arrays"=>\$mark_arrays);
unless ($#ARGV <= 0) {
    die "USAGE: [--nocolor --horizontal --mark-arrays] [filename]\n";
}
if ($nocolor) {
    $DumpMatch::NOCOLOR = 1;
}

my $what = 'comp_unit';
my $text;
{
local $/;
$text = Encode::decode('utf8', scalar <>);
}

my $r = Perl->new($text)->$what();
if ($yaml) {
    print Dump($r);
    exit;
} else {
    print dump_match($what=>$r,{vertical=>!$horizontal,mark_arrays=>$mark_arrays,visit_twice=>1}),"\n";
}

