#!/usr/local/bin/perl

use strict;
use warnings;
use utf8;
use English;
use STD;
use DumpMatch;
use Getopt::Long;
use File::Slurp;

my $nocolor = 0;
my $horizontal = 0;
my $yaml = 0;
my $mark_arrays;
my $clean_html = 0;
GetOptions(
    "nocolor"=>\$nocolor,
    "horizontal"=>\$horizontal,
    "yaml"=>\$yaml,
    "mark-arrays"=>\$mark_arrays,
    "clean-html"=>\$clean_html);

if ($#ARGV < 0) {
    die <<"HELP";
USAGE: 
    $PROGRAM_NAME [--nocolor --horizontal --mark-arrays --clean-html] filename [rule]
HELP
}
if ($nocolor) {
    $DumpMatch::NOCOLOR = 1;
}
my $file = shift;
my $what = shift // 'comp_unit';

my $r = STD->parsefile($file,$what);

=item highlight_match
=cut
sub highlight_match {
    my $name = shift;
    my $r = shift;
    my $opt = shift || {};
    my $events = [];
    traverse_match($r,$name,0,$events,$opt);
    highlight_perl6(${$r->{_orig}},$events,$opt);
}

=item highlight_perl6
=cut
sub highlight_perl6 {
    my ($orig,$events,$opt) = @_;
    my $str = "";
    my $at = 0;

    # slurp libraries and javascript to inline them
    my ($JQUERY_JS,$JS,$CSS) = (
        'jquery-1.2.6.pack.js', 
        'STD_syntax_highlight.js',
        'STD_syntax_highlight.css');
    my $jquery_js = qq{<script type="text/javascript" src="$JQUERY_JS"></script>};
    my $js = qq{<script type="text/javascript" src="$JS"></script>};
    my $css = qq{<link href="$CSS" rel="stylesheet" type="text/css">};
    if(!$clean_html) {
        $jquery_js = read_file($JQUERY_JS) 
            or die "Error while slurping file: $OS_ERROR\n";    
        $js = read_file($JS) 
            or die "Error while slurping file: $OS_ERROR\n";
        $css = read_file($CSS)
            or die "Error while slurping file: $OS_ERROR\n";
        $jquery_js = qq{<script type="text/javascript">\n$jquery_js\n</script>};
        $js = qq{<script type="text/javascript">\n$js\n</script>};
        $css = qq{<style type="text/css">\n$css\n</style>};
    }

    $str .= <<"HTML";
<html>
<head>
    <title>$PROGRAM_NAME $file</title>
    $css
    $jquery_js
    $js
</head>
<body>
	<div id="parseTreeOutput"></div>
    <pre>
HTML
 																	
    for (sort {$a->[0] <=> $b->[0] or $a->[4] <=> $b->[4]} @{$events}) {
        my $text = substr($orig,$at,$_->[0]-$at);
        $str .= escape_html($text);
        $at = $_->[0];
    
        if ($_->[1] eq 'from') {
            $str .= '<span class="'.$_->[2].'">';
        } elsif ($_->[1] eq 'to') {
            $str .=  '</span>';
        }
    }
    
    $str .= <<"HTML";
    </pre>
</body>
</html>
HTML

    $str;
}

=item escape_html
=cut
sub escape_html {
    my $str = shift;
    my %esc = (
        '<'     => '&lt;',
        '>'     => '&gt;',
        '"'     => '&quot;',
        '&'     => '&amp;'
    );
    my $re = join '|', map quotemeta, keys %esc;
    $str =~ s/($re)/$esc{$1}/g;
    return $str;
}

print highlight_match($what=>$r,{}) . "\n";

