#!/usr/local/bin/perl

use strict;
my $dir_to_test = shift @ARGV || '../../t/spec/';
my $fail = 0;
my $success = 0;
my @files = sort `find $dir_to_test -name '*.t'`;
chomp(@files);
$| = 1;

my $total = 0+@files;
my @failed;
for my $file (@files) {
    print $file, "\n";
    system "./tryfile $file >tryfile.out";
    if ($?) {
        push(@failed,$file);
	$fail++;
    }
    else {
	$success++;
	print "ok\n";
    }
}

printf "Passed $success/$total, %6.2f%%\n", $success/$total * 100;
print "Failed tests:\n";
for my $file (@failed) {
    print "$file\n";
}
