#!/usr/local/bin/perl

BEGIN { $ENV{STD5DEBUG} = -1; }
my $file = shift;

use STD5;
use utf8;
use YAML::XS;
use Encode;

print STDERR "Starting...\n";
my $what = 'comp_unit';
my $text = Encode::decode('utf8', `cat $file`);
my $r = Perl->new($text)->$what();
print Dump($r);
