#!/usr/bin/env perl

BEGIN { $ENV{STD5DEBUG} = 16383; }
use STD;
use utf8;
use YAML::XS;
use Encode;

print "Starting...\n";
my $what = 'foo';
my $text = "@ARGV";
my $r = STD->new($text)->$what();
print Dump($r);
