#!/usr/local/bin/perl

use STD;
use utf8;
use YAML::XS;
use Encode;

my $failures = 0;

if (not @ARGV) {
    @ARGV = <STDIN>;
    s/^[AU]+\s+// for @ARGV;
}

for my $file (@ARGV) {
    warn $file,"\n" if @ARGV > 1;
    eval {
	STD->parsefile($file);
    };
    if ($@) {
	warn $@;
	$failures++;
    }
}

exit $failures;
