class Test;
proto plan is export {*}
proto done is export {*}
proto is is export {*}
proto ok is export {*}
proto nok is export {*}
proto dies_ok is export {*}
proto lives_ok is export {*}
proto skip is export {*}
proto todo is export {*}
proto pass is export {*}
proto flunk is export {*}
proto force_todo is export {*}
proto use_ok is export {*}
proto isa_ok is export {*}
proto cmp_ok is export {*}
proto diag is export {*}
proto is_deeply is export {*}
proto isnt is export {*}
proto like is export {*}
proto unlike is export {*}
proto skip_rest is export {*}
proto eval_dies_ok is export {*}
proto eval_lives_ok is export {*}
proto approx is export {*}
proto is_approx is export {*}
proto throws_ok is export {*}
proto version_lt is export {*}
